name: xiaomi_weather_clone
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  animate_do: ^3.3.4
  auto_route: ^9.2.2
  bloc: ^8.1.4
  db_weather_repository:
    path: packages/db_weather_repository
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.15
  get_it: ^8.0.2
  hive_weather_api:
    path: packages/hive_weather_api
  hydrated_bloc: ^9.1.5
  intl: any
  json_annotation: ^4.9.0
  open_meteo_api:
    path: packages/open_meteo_api
  path_provider: ^2.1.5
  rxdart: ^0.28.0
  url_launcher: ^6.3.1
  url_strategy: ^0.3.0
  weather_repository:
    path: packages/weather_repository

dev_dependencies:
  auto_route_generator: ^9.0.0
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0
  mocktail: ^1.0.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/carlos_yllobre/
    - assets/icons/samodeh97/
    - assets/icons/Даниил/
